theme: ''
controlStyles:
  - target: Microsoft.UI.Xaml.Controls.Grid#PART_LayoutRoot
    styles:
      - Background=Transparent
      - HorizontalAlignment=Stretch
  - target: FileExplorerExtensions.FirstCrumbStackPanelControl#FirstCrumbStackPanel
    styles:
      - Visibility=1
  - target: Windows.UI.Xaml.Controls.Grid#RootCommandSearchGrid > Windows.UI.Xaml.Controls.Border#BorderElement
    styles:
      - Visibility=1
  - target: Microsoft.UI.Xaml.Controls.Primitives.NavigationViewItemPresenter#NavigationViewItemPresenter > Microsoft.UI.Xaml.Controls.Grid#LayoutRoot
    styles:
      - BorderThickness=$BorderThickness
      - Background:=$ButtonBackground
      - BorderBrush:=$ButtonBorder
  - target: Microsoft.UI.Xaml.Controls.Grid#CommandBarControlRootGrid
    styles:
      - Background:=Transparent
      - BorderBrush:=Transparent
  - target: Microsoft.UI.Xaml.Controls.CommandBar#FileExplorerCommandBar
    styles:
      - RenderTransform:=<TranslateTransform X="0" Y="0" />
      - HorizontalAlignment=Center
      - Margin=-4
      - Padding=10
  - target: Microsoft.UI.Xaml.Controls.CommandBar#FileExplorerSecondaryCommandBar
    styles:
      - HorizontalAlignment=Center
      - Margin=-4
      - Padding=10
      - Visibility=1
  - target: Microsoft.UI.Xaml.Controls.CommandBar#FileExplorerCommandBar > Microsoft.UI.Xaml.Controls.Grid#LayoutRoot > Microsoft.UI.Xaml.Controls.Grid#ContentRoot
    styles:
      - CornerRadius=$CornerRadius
      - BorderThickness=$BorderThickness
      - BorderBrush:=Transparent
      - Background:=Transparent
  - target: Microsoft.UI.Xaml.Controls.CommandBar#FileExplorerSecondaryCommandBar > Microsoft.UI.Xaml.Controls.Grid#LayoutRoot > Microsoft.UI.Xaml.Controls.Grid#ContentRoot
    styles:
      - BorderThickness=0
      - BorderBrush:=Transparent
      - Background:=Transparent
      - Visibility=1
  - target: Microsoft.UI.Xaml.Controls.Grid#NavigationBarControlGrid
    styles:
      - Background:=Transparent
      - BorderBrush:=Transparent
  - target: Microsoft.UI.Xaml.Controls.Grid#HomeViewRootGrid
    styles:
      - BorderBrush:=$ElementBorderBrush
      - CornerRadius=$ElementCornerRadius
      - BorderThickness=$ElementBorderThickness
      - Margin=4,0
      - // Background:=$ElementBG
  - target: 'FileExplorerExtensions.GalleryViewControl#GalleryViewControl > Grid  '
    styles:
      - BorderBrush:=$ElementBorderBrush
      - CornerRadius=$ElementCornerRadius
      - BorderThickness=$ElementBorderThickness
      - Margin=4,0
      - // Background:=$ElementBG
  - target: FileExplorerExtensions.GalleryViewControl#GalleryViewControl > Grid > Grid#GalleryRootGrid
    styles:
      - Background:=Transparent
  - target: ToolTip
    styles:
      - Background:=$ElementBG
      - BorderBrush:=$ElementBorderBrush
      - BorderThickness=$ElementBorderThickness
      - CornerRadius=$ElementCornerRadius
  - target: Grid#TabContainerGrid > Border#LeftBottomBorderLine
    styles:
      - Visibility=1
  - target: Grid#TabContainerGrid > Border#RightBottomBorderLine
    styles:
      - Visibility=1
  - target: TabViewItem > Grid#LayoutRoot
    styles:
      - Margin=5
      - Height=35
      - BorderThickness=$ElementBorderThickness
      - CornerRadius=$ElementCornerRadius
      - BorderBrush:=$ElementBorderBrush
  - target: TabViewItem > Grid#LayoutRoot > Canvas
    styles:
      - Visibility=1
  - target: TabViewItem > Grid#LayoutRoot > Grid#TabContainer
    styles:
      - Background=Transparent
      - BorderBrush=Transparent
  - target: TabViewItem > Grid#LayoutRoot@CommonStates
    styles:
      - Background@Selected:=$ElementBG
      - Background@PointerOverSelected:=$ButtonBackground
      - Background@PointerOver:=$ButtonBackground
      - Background@Normal:=$ElementBG
      - Background@PressedSelected:=$ButtonBackground
  - target: Grid#TabContainerGrid > Border#LeftBottomBorderLine
    styles:
      - Visibility=1
  - target: Grid#TabContainerGrid > Border#RightBottomBorderLine
    styles:
      - Visibility=1
  - target: Microsoft.UI.Xaml.Controls.Border#BottomBorderLine
    styles:
      - Visibility=1
  - target: Microsoft.UI.Xaml.Shapes.Path#LeftRadiusRenderArc
    styles:
      - Visibility=1
  - target: Microsoft.UI.Xaml.Shapes.Path#RightRadiusRenderArc
    styles:
      - Visibility=1
  - target: Microsoft.UI.Xaml.Controls.Grid#TabContainer
    styles:
      - Visibility=0
  - target: Microsoft.UI.Xaml.Controls.Viewbox#IconBox
    styles:
      - Visibility=1
  - target: Microsoft.UI.Xaml.Controls.Primitives.CommandBarFlyoutCommandBar > Grid#LayoutRoot > Grid#OuterContentRoot > Grid#ContentRoot > Grid#PrimaryItemsRoot
    styles:
      - Background:=$ElementBG
      - BorderThickness=$ElementBorderThickness
      - BorderBrush:=$ElementBorderBrush
      - CornerRadius=$ElementCornerRadius
  - target: Grid#OuterOverflowContentRootV2 > Grid#OverflowContentRoot > CommandBarOverflowPresenter#SecondaryItemsControl > Grid#LayoutRoot
    styles:
      - Background:=$ElementBG
      - BorderThickness=$ElementBorderThickness
      - BorderBrush:=$ElementBorderBrush
      - CornerRadius=$ElementCornerRadius
  - target: MenuFlyoutPresenter > Border
    styles:
      - Background:=$ElementBG
      - BorderThickness=$ElementBorderThickness
      - BorderBrush:=$ElementBorderBrush
      - CornerRadius=$ElementCornerRadius
  - target: CommandBarOverflowPresenter#SecondaryItemsControl > Grid#LayoutRoot
    styles:
      - Background:=$ElementBG
      - BorderThickness=$ElementBorderThickness
      - BorderBrush:=$ElementBorderBrush
      - CornerRadius=$ElementCornerRadius
  - target: Microsoft.UI.Xaml.Controls.AutoSuggestBox#FileExplorerSearchBox > Microsoft.UI.Xaml.Controls.Grid#LayoutRoot > Microsoft.UI.Xaml.Controls.TextBox#TextBox
    styles:
      - CornerRadius=$ElementCornerRadius
      - Background:=$ElementBG
      - BorderBrush:=$ElementBorderBrush
      - BorderThickness=$ElementBorderThickness
  - target: Microsoft.UI.Xaml.Controls.Grid#FileExplorerAddressBarGrid
    styles:
      - CornerRadius=$ElementCornerRadius
      - Background:=$ElementBG
      - BorderBrush:=$ElementBorderBrush
      - BorderThickness=$ElementBorderThickness
  - target: Microsoft.UI.Xaml.Controls.AutoSuggestBox#PART_AutoSuggestBox > Microsoft.UI.Xaml.Controls.Grid#LayoutRoot > Microsoft.UI.Xaml.Controls.TextBox#TextBox
    styles:
      - CornerRadius=$ElementCornerRadius
  - target: Microsoft.UI.Xaml.Controls.CommandBar#NavigationCommands
    styles:
      - HorizontalAlignment=Center
  - target: Microsoft.UI.Xaml.Controls.Grid#RootContainer
    styles:
      - Background:=Transparent
  - target: Microsoft.UI.Xaml.Controls.Border > Microsoft.UI.Xaml.Controls.Button#AddButton
    styles:
      - RenderTransform:=<TranslateTransform Y="-8" />
  - target: Microsoft.UI.Xaml.Controls.TextBlock#TextLabel
    styles:
      - Visibility=1
  - target: Microsoft.UI.Xaml.Controls.Grid#SubItemChevronPanel > Microsoft.UI.Xaml.Controls.FontIcon#SubItemChevron
    styles:
      - RenderTransform:=<TranslateTransform X="-5" Y="12" />
styleConstants:
  - Background=<WindhawkBlur BlurAmount="15" TintColor="#25323232" TintOpacity="0.2" />
  - MainContentBG=<SolidColorBrush Color="{ThemeResource SystemChromeAltHighColor}" Opacity="1" />
  - ButtonBackground=<SolidColorBrush Color="{ThemeResource SystemAccentColor}" Opacity="1" />
  - BorderThickness=0.3,1,0.3,0.3
  - ClockBG=<WindhawkBlur BlurAmount="20" TintColor="{ThemeResource SystemAccentColorLight2}" TintOpacity="0.3" />
  - ElementBG=<WindhawkBlur BlurAmount="20" TintColor="#202020" TintOpacity="0.2" />
  - ElementBorderThickness=0.3,0.3,0.3,1
  - ElementBorderBrush=<LinearGradientBrush StartPoint="0,0" EndPoint="0,1"><GradientStop Color="#50808080" Offset="1" /><GradientStop Color="#50606060" Offset="0.15" /></LinearGradientBrush>
  - BorderBrush=<LinearGradientBrush StartPoint="0,0" EndPoint="0,1"><GradientStop Color="#50808080" Offset="0.0" /><GradientStop Color="#50404040" Offset="0.25" /><GradientStop Color="#50808080" Offset="1" /></LinearGradientBrush>
  - ButtonBorder=<SolidColorBrush Color="{ThemeResource SystemAccentColorLight3}" Opacity="1" />
  - CornerRadius=10
  - ElementCornerRadius=6
resourceVariables:
  - variableKey: ''
    value: ''
explorerFrameContainerHeight: 0
